/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package employee.payroll.management.system;

import javax.swing.JOptionPane;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
/**
 *
 * @author kriaa
 */
public class EmployeeRegistration extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(EmployeeRegistration.class.getName());

    /**
     * Creates new form EmployeeRegistration
     */
    public EmployeeRegistration() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnback = new javax.swing.JButton();
        btnsave = new javax.swing.JButton();
        btnclear = new javax.swing.JButton();
        btnclose = new javax.swing.JButton();
        txtempid = new javax.swing.JTextField();
        txtempname = new javax.swing.JTextField();
        txtdep = new javax.swing.JTextField();
        txtdest = new javax.swing.JTextField();
        txtsal = new javax.swing.JTextField();
        txtph = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText(" EMPLOYEE REGISTRATION  FORM");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, 491, 50));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Employee ID");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 90, 120, 31));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Employee Name");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 150, 120, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Department");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 220, 120, 31));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Designation");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 280, 120, 30));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Basic Salary");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 340, 120, 30));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Phone");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 390, 120, 32));

        btnback.setBackground(new java.awt.Color(102, 0, 0));
        btnback.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        btnback.setForeground(new java.awt.Color(255, 255, 255));
        btnback.setText(" BACK");
        btnback.addActionListener(this::btnbackActionPerformed);
        getContentPane().add(btnback, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 520, 95, 50));

        btnsave.setBackground(new java.awt.Color(102, 0, 0));
        btnsave.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        btnsave.setForeground(new java.awt.Color(255, 255, 255));
        btnsave.setText(" SAVE");
        btnsave.addActionListener(this::btnsaveActionPerformed);
        getContentPane().add(btnsave, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 520, 96, 50));

        btnclear.setBackground(new java.awt.Color(102, 0, 0));
        btnclear.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        btnclear.setForeground(new java.awt.Color(255, 255, 255));
        btnclear.setText("CLEAR ");
        btnclear.addActionListener(this::btnclearActionPerformed);
        getContentPane().add(btnclear, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 520, 96, 50));

        btnclose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/close icon.png"))); // NOI18N
        btnclose.addActionListener(this::btncloseActionPerformed);
        getContentPane().add(btnclose, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 0, 70, 48));

        txtempid.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtempid.addActionListener(this::txtempidActionPerformed);
        getContentPane().add(txtempid, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 90, 438, 38));

        txtempname.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtempname.addActionListener(this::txtempnameActionPerformed);
        getContentPane().add(txtempname, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 150, 438, 39));

        txtdep.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtdep.addActionListener(this::txtdepActionPerformed);
        getContentPane().add(txtdep, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 210, 438, 37));

        txtdest.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(txtdest, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 270, 438, 38));

        txtsal.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(txtsal, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 330, 438, 37));

        txtph.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(txtph, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 390, 438, 38));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/student_registration.jpeg"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2, -4, 1000, 670));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtempnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtempnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtempnameActionPerformed

    private void txtdepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdepActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdepActionPerformed

    private void btncloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncloseActionPerformed
        // TODO add your handling code here:
         int yes=JOptionPane.showConfirmDialog(this, "Are you really close this page ?", "Logut",JOptionPane.YES_NO_OPTION);
       if(JOptionPane.YES_OPTION==yes){
            System.exit(0);
       }
    }//GEN-LAST:event_btncloseActionPerformed

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
        // TODO add your handling code here:
        new Home().setVisible(true);
this.dispose();
    }//GEN-LAST:event_btnbackActionPerformed

    private void btnclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclearActionPerformed
        // TODO add your handling code here:
        txtempid.setText("");
    txtempname.setText("");
    txtdep.setText("");
    txtdest.setText("");
    txtsal.setText("");
    txtph.setText("");


    }//GEN-LAST:event_btnclearActionPerformed

    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveActionPerformed
        // TODO add your handling code here:
                                               

    String id = txtempid.getText();
    String name = txtempname.getText();
    String department = txtdep.getText();
    String designation = txtdest.getText();
    String phone = txtph.getText();

    if (id.isEmpty() || name.isEmpty() || department.isEmpty()
            || designation.isEmpty() || txtsal.getText().isEmpty()
            || phone.isEmpty()) {

        JOptionPane.showMessageDialog(this,
                "Please fill all fields");
        return;
    }

    try {

        double salary = Double.parseDouble(txtsal.getText());

        Connection con = Connect.Connection();

        String sql = "INSERT INTO employee "
                + "(id, name, department, designation, phone, basic_salary) "
                + "VALUES (?, ?, ?, ?, ?, ?)";

        PreparedStatement pst = con.prepareStatement(sql);

        pst.setString(1, id);
        pst.setString(2, name);
        pst.setString(3, department);
        pst.setString(4, designation);
        pst.setString(5, phone);
        pst.setDouble(6, salary);

        pst.executeUpdate();

        JOptionPane.showMessageDialog(this,
                "Employee Registered Successfully!");

        pst.close();
        con.close();

    } catch (NumberFormatException e) {

        JOptionPane.showMessageDialog(this,
                "Please enter valid salary");

    } catch (SQLException e) {

        JOptionPane.showMessageDialog(this,
                "Database Error: " + e.getMessage());
    }

    }//GEN-LAST:event_btnsaveActionPerformed

    private void txtempidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtempidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtempidActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new EmployeeRegistration().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnback;
    private javax.swing.JButton btnclear;
    private javax.swing.JButton btnclose;
    private javax.swing.JButton btnsave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField txtdep;
    private javax.swing.JTextField txtdest;
    private javax.swing.JTextField txtempid;
    private javax.swing.JTextField txtempname;
    private javax.swing.JTextField txtph;
    private javax.swing.JTextField txtsal;
    // End of variables declaration//GEN-END:variables
}
