/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package employee.payroll.management.system;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
/**
 *
 * @author kriaa
 */
public class Home extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Home.class.getName());

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnhome = new javax.swing.JButton();
        btnregistration = new javax.swing.JButton();
        btnemp = new javax.swing.JButton();
        btnpay = new javax.swing.JButton();
        btnsalaryreport = new javax.swing.JButton();
        btnlogout = new javax.swing.JButton();
        btnclose = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(204, 51, 0));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 0));
        jLabel1.setText("Welcome  to  Home  Page");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 410, 50));

        btnhome.setBackground(new java.awt.Color(255, 153, 153));
        btnhome.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnhome.setText(" Home");
        btnhome.addActionListener(this::btnhomeActionPerformed);
        getContentPane().add(btnhome, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 130, 240, 40));

        btnregistration.setBackground(new java.awt.Color(255, 153, 153));
        btnregistration.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnregistration.setText("Employee Registration");
        btnregistration.addActionListener(this::btnregistrationActionPerformed);
        getContentPane().add(btnregistration, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 190, 240, 40));

        btnemp.setBackground(new java.awt.Color(255, 153, 153));
        btnemp.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnemp.setText("Employee Details");
        btnemp.addActionListener(this::btnempActionPerformed);
        getContentPane().add(btnemp, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 250, 240, 40));

        btnpay.setBackground(new java.awt.Color(255, 153, 153));
        btnpay.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnpay.setText("Payroll");
        btnpay.addActionListener(this::btnpayActionPerformed);
        getContentPane().add(btnpay, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 310, 240, 40));

        btnsalaryreport.setBackground(new java.awt.Color(255, 153, 153));
        btnsalaryreport.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnsalaryreport.setText("Salary Report");
        btnsalaryreport.addActionListener(this::btnsalaryreportActionPerformed);
        getContentPane().add(btnsalaryreport, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 370, 240, 40));

        btnlogout.setBackground(new java.awt.Color(255, 153, 153));
        btnlogout.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnlogout.setText("Logout");
        btnlogout.addActionListener(this::btnlogoutActionPerformed);
        getContentPane().add(btnlogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 440, 240, 40));

        btnclose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/close icon.png"))); // NOI18N
        btnclose.addActionListener(this::btncloseActionPerformed);
        getContentPane().add(btnclose, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 10, 48, 48));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/WhatsApp Image 2026-10-09 at 05.53.25.jpeg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, 880, 600));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/WhatsApp Image 2026-10-09 at 05.53.25.jpeg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnempActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnempActionPerformed
        // TODO add your handling code here:
        new EmployeeDetails().setVisible(true);
this.dispose();
    }//GEN-LAST:event_btnempActionPerformed

    private void btnpayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpayActionPerformed
        // TODO add your handling code here:
        new Payroll().setVisible(true);
    this.dispose();

    }//GEN-LAST:event_btnpayActionPerformed

    private void btnregistrationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregistrationActionPerformed
        // TODO add your handling code here:
        new EmployeeRegistration().setVisible(true);
this.dispose();
    }//GEN-LAST:event_btnregistrationActionPerformed

    private void btnhomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhomeActionPerformed
        // TODO add your handling code here:
                                              

    new Home().setVisible(true);
    this.dispose();


    }//GEN-LAST:event_btnhomeActionPerformed

    private void btncloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncloseActionPerformed
        // TODO add your handling code here:
         int yes=JOptionPane.showConfirmDialog(this, "Are you really close this page ?", "Logut",JOptionPane.YES_NO_OPTION);
       if(JOptionPane.YES_OPTION==yes){
            System.exit(0);
       }
    }//GEN-LAST:event_btncloseActionPerformed

    private void btnlogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlogoutActionPerformed
        // TODO add your handling code here:
        int yes=JOptionPane.showConfirmDialog(this, "Are you really Logout ?", "Logut",JOptionPane.YES_NO_OPTION);
       if(JOptionPane.YES_OPTION==yes){
            System.exit(0);
       }
    }//GEN-LAST:event_btnlogoutActionPerformed

    private void btnsalaryreportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalaryreportActionPerformed
        // TODO add your handling code here:
        

   
    new SalaryReport().setVisible(true);
    this.dispose();

    

    }//GEN-LAST:event_btnsalaryreportActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Home().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnclose;
    private javax.swing.JButton btnemp;
    private javax.swing.JButton btnhome;
    private javax.swing.JButton btnlogout;
    private javax.swing.JButton btnpay;
    private javax.swing.JButton btnregistration;
    private javax.swing.JButton btnsalaryreport;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
