/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package employee.payroll.management.system;

import javax.swing.JOptionPane;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author kriaa
 */
public class Payroll extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Payroll.class.getName());

    /**
     * Creates new form Payroll
     */
    public Payroll() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtempid = new javax.swing.JTextField();
        txtempname = new javax.swing.JTextField();
        txtsal = new javax.swing.JTextField();
        txtallowance = new javax.swing.JTextField();
        txtdeduction = new javax.swing.JTextField();
        txtnet = new javax.swing.JTextField();
        btnsearch = new javax.swing.JButton();
        btnclose = new javax.swing.JButton();
        btnsave = new javax.swing.JButton();
        btnclear = new javax.swing.JButton();
        btnback = new javax.swing.JButton();
        btncalculate = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 0));
        jLabel1.setText(" EMPLOYEE PAYROLL ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(363, 26, 330, 70));

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Employee ID");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 140, 40));

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Employee Name");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 195, 160, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Basic Salary");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, 130, 60));

        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Allowance");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 310, 130, 40));

        jLabel6.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Deduction");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 360, 220, 60));

        jLabel7.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Net Salary");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 420, 130, 60));

        txtempid.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        getContentPane().add(txtempid, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 120, 390, 50));

        txtempname.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        getContentPane().add(txtempname, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 180, 390, 50));

        txtsal.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        getContentPane().add(txtsal, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 240, 390, 50));

        txtallowance.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        getContentPane().add(txtallowance, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 300, 390, 50));

        txtdeduction.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        getContentPane().add(txtdeduction, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 370, 390, 50));

        txtnet.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        getContentPane().add(txtnet, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 430, 390, 50));

        btnsearch.setBackground(new java.awt.Color(255, 255, 0));
        btnsearch.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        btnsearch.setForeground(new java.awt.Color(51, 51, 0));
        btnsearch.setText("Search");
        btnsearch.addActionListener(this::btnsearchActionPerformed);
        getContentPane().add(btnsearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 120, 130, 50));

        btnclose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/close icon.png"))); // NOI18N
        btnclose.addActionListener(this::btncloseActionPerformed);
        getContentPane().add(btnclose, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 0, 60, 60));

        btnsave.setBackground(new java.awt.Color(255, 255, 0));
        btnsave.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        btnsave.setForeground(new java.awt.Color(51, 0, 51));
        btnsave.setText("Save");
        btnsave.addActionListener(this::btnsaveActionPerformed);
        getContentPane().add(btnsave, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 510, 130, 50));

        btnclear.setBackground(new java.awt.Color(255, 255, 0));
        btnclear.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        btnclear.setForeground(new java.awt.Color(51, 51, 0));
        btnclear.setText("Clear");
        btnclear.addActionListener(this::btnclearActionPerformed);
        getContentPane().add(btnclear, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 580, 130, 50));

        btnback.setBackground(new java.awt.Color(255, 255, 0));
        btnback.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        btnback.setForeground(new java.awt.Color(51, 0, 0));
        btnback.setText("Back");
        btnback.addActionListener(this::btnbackActionPerformed);
        getContentPane().add(btnback, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 510, 140, 50));

        btncalculate.setBackground(new java.awt.Color(255, 255, 0));
        btncalculate.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        btncalculate.setForeground(new java.awt.Color(51, 0, 51));
        btncalculate.setText("Calculate");
        btncalculate.addActionListener(this::btncalculateActionPerformed);
        getContentPane().add(btncalculate, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 580, 140, 50));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/WhatsApp Image 2026-10-09 at 04.31.11.jpeg"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2, -4, 1200, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveActionPerformed
        // TODO add your handling code here:
                                            

    String id = txtempid.getText();

    if (id.isEmpty() || txtnet.getText().isEmpty()) {
        JOptionPane.showMessageDialog(this,
                "Please enter Employee ID and calculate salary first");
        return;
    }

    try {
        double basic = Double.parseDouble(txtsal.getText());
        double allowance = Double.parseDouble(txtallowance.getText());
        double deduction = Double.parseDouble(txtdeduction.getText());
        double net = Double.parseDouble(txtnet.getText());

        Connection con = Connect.Connection();

        String sql = "UPDATE employee SET allowance=?, deduction=?, net_salary=? WHERE id=?";

        PreparedStatement pst = con.prepareStatement(sql);

        pst.setDouble(1, allowance);
        pst.setDouble(2, deduction);
        pst.setDouble(3, net);
        pst.setString(4, id);

        int result = pst.executeUpdate();

        if (result > 0) {
            JOptionPane.showMessageDialog(this,
                    "Payroll Saved Successfully!");
        } else {
            JOptionPane.showMessageDialog(this,
                    "Employee ID not found. Please search first.");
        }

        pst.close();
        con.close();

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this,
                "Please enter valid salary values");

    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this,
                "Database Error: " + e.getMessage());
    }

    }//GEN-LAST:event_btnsaveActionPerformed

    private void btncloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncloseActionPerformed
        // TODO add your handling code here:
        int yes=JOptionPane.showConfirmDialog(this, "Are you really close this page ?", "Logut",JOptionPane.YES_NO_OPTION);
       if(JOptionPane.YES_OPTION==yes){
            System.exit(0);
       }
    }//GEN-LAST:event_btncloseActionPerformed

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
        // TODO add your handling code here:
        
    new Home().setVisible(true);
    this.dispose();


    }//GEN-LAST:event_btnbackActionPerformed

    private void btncalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncalculateActionPerformed
        // TODO add your handling code here:
       
    try {
        double basic = Double.parseDouble(txtsal.getText());
        double allowance = Double.parseDouble(txtallowance.getText());
        double deduction = Double.parseDouble(txtdeduction.getText());

        if (basic < 0 || allowance < 0 || deduction < 0) {
            JOptionPane.showMessageDialog(this, "Salary values cannot be negative");
            return;
        }

        double netSalary = basic + allowance - deduction;

        txtnet.setText(String.valueOf(netSalary));

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this,
                "Please enter valid Basic Salary, Allowance and Deduction");
    }

    }//GEN-LAST:event_btncalculateActionPerformed

    private void btnclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclearActionPerformed
        // TODO add your handling code here:
        
    txtempid.setText("");
    txtempname.setText("");
    txtsal.setText("");
    txtallowance.setText("");
    txtdeduction.setText("");
    txtnet.setText("");


    }//GEN-LAST:event_btnclearActionPerformed

    private void btnsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsearchActionPerformed
        // TODO add your handling code here:
         String id = txtempid.getText().trim();

    if (id.isEmpty()) {
        JOptionPane.showMessageDialog(this,
                "Please enter Employee ID");
        return;
    }

    try {
        Connection con = Connect.Connection();

        String sql = "SELECT name, basic_salary FROM employee WHERE id = ?";
        PreparedStatement pst = con.prepareStatement(sql);

        pst.setString(1, id);

        ResultSet rs = pst.executeQuery();

        if (rs.next()) {

            txtempname.setText(rs.getString("name"));
            txtsal.setText(String.valueOf(rs.getDouble("basic_salary")));

            JOptionPane.showMessageDialog(this,
                    "Employee Found Successfully!");

        } else {

            JOptionPane.showMessageDialog(this,
                    "Employee ID not found");

            txtempname.setText("");
            txtsal.setText("");
        }

        rs.close();
        pst.close();
        con.close();

    } catch (SQLException e) {

        JOptionPane.showMessageDialog(this,
                "Database Error: " + e.getMessage());
    }
    }//GEN-LAST:event_btnsearchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Payroll().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnback;
    private javax.swing.JButton btncalculate;
    private javax.swing.JButton btnclear;
    private javax.swing.JButton btnclose;
    private javax.swing.JButton btnsave;
    private javax.swing.JButton btnsearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField txtallowance;
    private javax.swing.JTextField txtdeduction;
    private javax.swing.JTextField txtempid;
    private javax.swing.JTextField txtempname;
    private javax.swing.JTextField txtnet;
    private javax.swing.JTextField txtsal;
    // End of variables declaration//GEN-END:variables
}
