/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package employee.payroll.management.system;

import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author kriaa
 */
public class SalaryReport extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(SalaryReport.class.getName());

    /**
     * Creates new form SalaryReport
     */
    public SalaryReport() {
     initComponents();
        
    
    tablesalary.setShowGrid(true);
    tablesalary.setShowHorizontalLines(true);
    tablesalary.setShowVerticalLines(true);
    tablesalary.setGridColor(java.awt.Color.BLACK);
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtsearch = new javax.swing.JTextField();
        btnsearch = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablesalary = new javax.swing.JTable();
        btnrefresh = new javax.swing.JButton();
        btnback = new javax.swing.JButton();
        btnclose = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 0));
        jLabel1.setText("SALARY REPORT");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 437, 76));

        jLabel2.setBackground(new java.awt.Color(255, 255, 0));
        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 0));
        jLabel2.setText("Employee ID");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, 129, 55));

        txtsearch.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        getContentPane().add(txtsearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 120, 410, 55));

        btnsearch.setBackground(new java.awt.Color(204, 0, 0));
        btnsearch.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        btnsearch.setForeground(new java.awt.Color(255, 255, 255));
        btnsearch.setText("Search");
        btnsearch.addActionListener(this::btnsearchActionPerformed);
        getContentPane().add(btnsearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 120, 195, 55));

        tablesalary.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tablesalary.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Employee ID", "Employee Name", "Basic Salary", "Allowance", "Deduction", "Net Salary"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablesalary);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, 950, 510));

        btnrefresh.setBackground(new java.awt.Color(204, 0, 0));
        btnrefresh.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        btnrefresh.setForeground(new java.awt.Color(255, 255, 255));
        btnrefresh.setText("Refresh");
        btnrefresh.addActionListener(this::btnrefreshActionPerformed);
        getContentPane().add(btnrefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 770, 134, 46));

        btnback.setBackground(new java.awt.Color(204, 0, 0));
        btnback.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        btnback.setForeground(new java.awt.Color(255, 255, 255));
        btnback.setText("Back");
        btnback.addActionListener(this::btnbackActionPerformed);
        getContentPane().add(btnback, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 770, 132, 46));

        btnclose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/close icon.png"))); // NOI18N
        btnclose.addActionListener(this::btncloseActionPerformed);
        getContentPane().add(btnclose, new org.netbeans.lib.awtextra.AbsoluteConstraints(1299, 0, 61, 52));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/WhatsApp Image 2026-10-09 at 06.08.22.jpeg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1360, 660));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/WhatsApp Image 2026-10-09 at 06.08.22.jpeg"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2, 660, 1350, 200));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btncloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncloseActionPerformed
        // TODO add your handling code here:
          int yes=JOptionPane.showConfirmDialog(this, "Are you really close this page ?", "Logut",JOptionPane.YES_NO_OPTION);
       if(JOptionPane.YES_OPTION==yes){
            System.exit(0);
       }
    }//GEN-LAST:event_btncloseActionPerformed

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
        // TODO add your handling code here:
        new Home().setVisible(true);
    this.dispose();
    }//GEN-LAST:event_btnbackActionPerformed

    private void btnrefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrefreshActionPerformed
        // TODO add your handling code here:
        try {
    Connection con = Connect.Connection();

    String sql = "SELECT id, name, basic_salary, allowance, deduction, net_salary "
               + "FROM employee";

    PreparedStatement pst = con.prepareStatement(sql);
    ResultSet rs = pst.executeQuery();

    DefaultTableModel model =
            (DefaultTableModel) tablesalary.getModel();

    model.setRowCount(0);

    while (rs.next()) {
        model.addRow(new Object[]{
            rs.getString("id"),
            rs.getString("name"),
            rs.getDouble("basic_salary"),
            rs.getDouble("allowance"),
            rs.getDouble("deduction"),
            rs.getDouble("net_salary")
        });
    }

    rs.close();
    pst.close();
    con.close();

    JOptionPane.showMessageDialog(this,
            "Salary Report Refreshed Successfully!");

} catch (SQLException e) {
    JOptionPane.showMessageDialog(this,
            "Database Error: " + e.getMessage());
}
    }//GEN-LAST:event_btnrefreshActionPerformed

    private void btnsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsearchActionPerformed
        // TODO add your handling code here:
        
String id = txtsearch.getText().trim();

if (id.isEmpty()) {
    JOptionPane.showMessageDialog(this, "Please enter Employee ID");
    return;
}

try {
    Connection con = Connect.Connection();

    String sql = "SELECT id, name, basic_salary, allowance, deduction, net_salary "
               + "FROM employee WHERE id = ?";

    PreparedStatement pst = con.prepareStatement(sql);
    pst.setString(1, id);

    ResultSet rs = pst.executeQuery();

    DefaultTableModel model =
            (DefaultTableModel) tablesalary.getModel();

    model.setRowCount(0);

    if (rs.next()) {
        model.addRow(new Object[]{
            rs.getString("id"),
            rs.getString("name"),
            rs.getDouble("basic_salary"),
            rs.getDouble("allowance"),
            rs.getDouble("deduction"),
            rs.getDouble("net_salary")
        });
    } else {
        JOptionPane.showMessageDialog(this, "Employee ID not found");
    }

    rs.close();
    pst.close();
    con.close();

} catch (SQLException e) {
    JOptionPane.showMessageDialog(this,
            "Database Error: " + e.getMessage());
}
    }//GEN-LAST:event_btnsearchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new SalaryReport().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnback;
    private javax.swing.JButton btnclose;
    private javax.swing.JButton btnrefresh;
    private javax.swing.JButton btnsearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablesalary;
    private javax.swing.JTextField txtsearch;
    // End of variables declaration//GEN-END:variables

    
}
